# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.website_global_datas:
        class: AppBundle\Service\WebsiteGlobalDatas
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@snc_redis.default"]
        public: true
    app.s3_uploader:
        class: AppBundle\Service\S3Uploader
        arguments: ["@pr.amazon_s3", '%amazon.s3.bucket%', '%amazon.s3.directory%']
        public: true
    app.mailer:
        class: AppBundle\Service\Mailer
        arguments: ['@mailer', '@templating', '%mailer.reply%', '%mailer.noreply%', '%mailer.name%', "@doctrine.orm.entity_manager", "@service_container", "@snc_redis.default"]
        public: true
    app.pr_employee_api:
        class: AppBundle\Service\PrEmployeeApi
        arguments: ['%pr_employee.api_key%', '%pr_employee.base_url%']
        public: true
    app.event.notification:
        class: AppBundle\Event\NotificationEvent
        arguments: ["@doctrine.orm.entity_manager"]
    app.event_subscriber.action:
        class: AppBundle\EventSubscriber\ActionSubscriber
        arguments: ['@app.website_global_datas', '@security.token_storage']
        public: true
