<?php

namespace AppBundle\Repository;

/**
 * AdditionalPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalPictureRepository extends \Doctrine\ORM\EntityRepository
{
}
