<?php

namespace AppBundle\Repository;

/**
 * BusinessDriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessDriverRepository extends \Doctrine\ORM\EntityRepository
{
}
