<?php

namespace AppBundle\Repository;

/**
 * CanvasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanvasRepository extends \Doctrine\ORM\EntityRepository
{
}
