<?php

namespace AppBundle\Repository;

/**
 * ConsumerOpportunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumerOpportunityRepository extends \Doctrine\ORM\EntityRepository
{
}
