<?php

namespace AppBundle\Repository;

/**
 * EntityGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityGroupRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all for json.
     *
     * @return array
     */
    public function getAllForJson()
    {
        $all_entity_groups = $this->getEntityManager()->getRepository('AppBundle:EntityGroup')->findBy(array(), array('sort_order' => 'ASC'));
        $ret = array();
        foreach ($all_entity_groups as $entity_group) {
            $ret[] = array(
                'id' => $entity_group->getId(),
                'text' => $entity_group->getTitle(),
            );
        }
        return $ret;
    }
}
