<?php

namespace AppBundle\Repository;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{


    public function getFeedbacksForInnovation($inno_id, $offset = 0, $limit = 20) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb->select([
            'f',
            'fi',
            'user',
        ])
            ->from('AppBundle:Feedback', 'f')
            ->leftJoin('f.invitation', 'fi')
            ->leftJoin('fi.innovation', 'innovation')
            ->leftJoin('fi.user', 'user')
            ->where('innovation.id = :inno_id')
            ->orderBy('f.id', 'desc')
            ->setParameter('inno_id', $inno_id)
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true, 3600)
            ->getResult();
    }

    public function getCountFeedbacksForInnovation($inno_id) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return intval($qb->select(['count(f)'])
            ->from('AppBundle:Feedback', 'f')
            ->leftJoin('f.invitation', 'fi')
            ->leftJoin('fi.innovation', 'innovation')
            ->where('innovation.id = :inno_id')
            ->setParameter('inno_id', $inno_id)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true, 3600)
            ->getSingleScalarResult());
    }

}
