<?php

namespace AppBundle\Repository;

/**
 * MDCompetitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MDCompetitorRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns recommandations for a user and the current period.
     * 
     * @param \AppBundle\Entity\User $user
     * @return array
     */
    function getCompetitorsForUser($user) {
        $periode = $this->getEntityManager()
            ->getRepository('AppBundle:Settings')
            ->getCurrentSettings()
            ->getCurrentFinancialDate();
        
        return $this->findBy([
            'user' => $user,
            'periode' => $periode
        ]);
    }
}
