<?php

namespace AppBundle\Repository;

/**
 * MDRecommandationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MDRecommandationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns recommandations for a user and the current period.
     * 
     * @param \AppBundle\Entity\User $user
     * @param string period
     * @return \AppBundle\Entity\MDRecommandation
     */
    function getRecommandationForUser($user, $period = null) {
        if(!$period) {
            $period = $this->getEntityManager()
                ->getRepository('AppBundle:Settings')
                ->getCurrentSettings()
                ->getCurrentFinancialDate();
        }
        
        return $this->findOneBy([
            'user' => $user,
            'periode' => $period
        ]);
    }
}
