<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Innovation;
use AppBundle\Entity\Metrics;
use AppBundle\Entity\User;

/**
 * MetricsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetricsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Create metrics.
     *
     * @param User $user
     * @param Innovation $innovation
     * @param string $action
     * @param null|string $key
     * @param null|array $data
     * @return Metrics
     */
    public function createMetrics($user, $innovation, $action, $key = null, $data = null)
    {
        $em = $this->getEntityManager();
        if($key){
            $metrics = $em->getRepository('AppBundle:Metrics')->findOneBy(array('key' => $key, 'action' => $action));
            if($metrics){
                return $metrics;
            }
        }
        $metrics = new Metrics();
        $metrics->setUser($user);
        if($innovation) {
            $metrics->setInnovation($innovation);
        }
        $metrics->setAction($action);
        if($key){
            $metrics->setKey($key);
        }
        $metrics->setDataArray($data);
        $em->persist($metrics);
        $em->flush();
        return $metrics;
    }
}
