<?php

namespace AppBundle\Repository;

/**
 * MomentOfConsumptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MomentOfConsumptionRepository extends \Doctrine\ORM\EntityRepository
{
}
