<?php

namespace AppBundle\Repository;

/**
 * OpenQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpenQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
