<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Activity;
use AppBundle\Entity\Innovation;
use AppBundle\Entity\PerformanceReview;
use AppBundle\Entity\User;

/**
 * PerformanceReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerformanceReviewRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Create or update PerformanceReview.
     *
     * @param User $user
     * @param Innovation $innovation
     * @param string $libelle
     * @param string $value
     * @param bool $create_activity
     * @return PerformanceReview
     */
    public function createOrUpdatePerformanceReview($user, $innovation, $libelle, $value,  $create_activity = true){
        if(!$libelle || !$user || !$innovation){
            return false;
        }
        $em = $this->getEntityManager();
        $performanceReview = $innovation->getPerformanceReviewsByKey($libelle);
        if (!$performanceReview) {
            $performanceReview = new PerformanceReview();
        }
        $old_value = $performanceReview->getValue();
        $performanceReview->setInnovation($innovation);
        $performanceReview->setKey($libelle);
        $performanceReview->setValue($value);

        $em->persist($performanceReview);
        $em->flush();

        if ($create_activity && $old_value != $value) {
            $em->getRepository('AppBundle:Activity')->createActivity($user, $innovation, Activity::ACTION_INNOVATION_UPDATED, $libelle, null, $old_value, $value);
        }
        return $performanceReview;
    }
}
