<?php

namespace AppBundle\Repository;

/**
 * PortfolioProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
