<?php

namespace AppBundle\Repository;

/**
 * SearchHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
