<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Settings;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get current settings.
     *
     * @return Settings
     */
    public function getCurrentSettings()
    {
        $em = $this->getEntityManager();
        return $em->getRepository("AppBundle:Settings")->findOneById(1);
    }

    /**
     * Update current settings ping.
     *
     */
    public function updateCurrentSettingsPing()
    {
        $em = $this->getEntityManager();
        $settings = $this->getCurrentSettings();
        $settings->updatePing();
        $em->persist($settings);
        $em->flush();
        $em->clear();
    }

    /**
     * Update settings cache_version.
     *
     */
    public function updateSettingsCacheVersion()
    {
        $em = $this->getEntityManager();
        $settings = $this->getCurrentSettings();
        $settings->updateCacheVersion();
        $em->persist($settings);
        $em->flush();
        $em->clear();
    }

    /**
     * Get website other datas.
     * 
     * @return array
     */
    public function getWebsiteOtherDatas(){
        $em = $this->getEntityManager();
        return array(
            'brands_json' => $em->getRepository("AppBundle:Brand")->getAllForJson(),
            'entities_json' => $em->getRepository("AppBundle:Entity")->getAllForJson(),
            'contacts_json' => $em->getRepository("AppBundle:User")->getAllForJson(),
            'citations' => self::getAllCitations(),
            'perimeter_json' => $em->getRepository("AppBundle:EntityGroup")->getAllForJson()
        );
    }

    /**
     * Get all citations.
     *
     * @return array
     */
    public static function getAllCitations(){
        $citations = array();
        $citations[] = array(
            'content' => "It always seems impossible until it’s done.",
            'author' => "Nelson Mandela"
        );
        $citations[] = array(
            'content' => "Genius is one percent inspiration and ninety-nine percent perspiration.",
            'author' => "Thomas Edison"
        );
        $citations[] = array(
            'content' => "Innovation is change that unlocks new value.",
            'author' => "Jamie Notter"
        );
        $citations[] = array(
            'content' => "If you are not failing every now and again, it’s a sign you’re not doing anything very innovative.",
            'author' => "Woody Allen"
        );
        $citations[] = array(
            'content' => "Insanity: doing the same thing over and over again and expecting different results.",
            'author' => "Albert Einstein"
        );
        $citations[] = array(
            'content' => "Creativity starts when you a cut a zero from your budget.",
            'author' => "Jamie Lerner"
        );
        $citations[] = array(
            'content' => "Logic will take you from A to B. Imagination will take you anywhere.",
            'author' => "Albert Einstein"
        );
        $citations[] = array(
            'content' => "The value of an idea lies in the using of it.",
            'author' => "Thomas Edison"
        );
        return $citations;
    }

    /**
     * Get random citation.
     *
     * @return array
     */
    public static function getRandomCitation(){
        $citations = self::getAllCitations();
        $k = array_rand($citations);
        return $citations[$k];
    }
}
