<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Stage;

/**
 * StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get inner stages.
     *
     * @return array
     */
    public function getInnerStages()
    {
        return $this->getEntityManager()->getRepository('AppBundle:Stage')->findBy(array('id' => array(
            Stage::STAGE_ID_DISCOVER,
            Stage::STAGE_ID_IDEATE,
            Stage::STAGE_ID_EXPERIMENT,
            Stage::STAGE_ID_INCUBATE,
            Stage::STAGE_ID_SCALE_UP,
        )));
    }

    /**
     * Get out stages.
     *
     * @return array
     */
    public function getOutStages()
    {
        return $this->getEntityManager()->getRepository('AppBundle:Stage')->findBy(array('id' => array(
            Stage::STAGE_ID_DISCONTINUED,
            Stage::STAGE_ID_PERMANENT_RANGE,
        )));
    }
}
