<?php

namespace AppBundle\Repository;

/**
 * UserSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSkillRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Remove skill for user.
     *
     * @param $skill
     * @param $user
     * @return bool
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function removeSkillForUser($skill, $user){
        if(!$skill || !$user){
            return false;
        }
        $em = $this->getEntityManager();
        $userSkills = $em->getRepository('AppBundle:UserSkill')->findBy(['user' => $user, 'skill' => $skill]);
        foreach ($userSkills as $userSkill){
            $em->remove($userSkill);
            $em->flush();

        }
        return true;
    }
}
