<?php

namespace AppBundle\Repository;

/**
 * UserEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
