pr_auth:
    resource: "@PrAuthBundle/Controller/"
    type:     annotation
    prefix:   /
    schemes:  ['%http_protocol%']

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    schemes:  ['%http_protocol%']

# All theses routes are unused for now
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    schemes:  ['%http_protocol%']

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    schemes:  ['%http_protocol%']

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    schemes:  ['%http_protocol%']

dtc_queue:
    resource: '@DtcQueueBundle/Resources/config/routing.yml'
    schemes:  ['%http_protocol%']
dtc_grid:
    resource: '@DtcGridBundle/Resources/config/routing.yml'
    schemes:  ['%http_protocol%']

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# Must be the last rule
pageNotFound:
    path:  /{path}
    defaults: { _controller: AppBundle:Global:pageNotFound, path: '' }
    requirements:
        path: .*